name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  BINDLE_SERVER_URL: https://bindle.deislabs.io/v1

jobs:
  publish:
    name: Build and publish release assets

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust bits
      run: rustup target add wasm32-wasi

### BEGIN CUSTOM KLUDGE

    - name: Trust Bindle server cert
      run: |
        mkdir certs
        wget https://letsencrypt.org/certs/lets-encrypt-r3.pem -q -O ./certs/lets-encrypt-r3.pem
        openssl x509 -in ./certs/lets-encrypt-r3.pem -inform PEM -out ./certs/lets-encrypt-r3.crt
        wget https://letsencrypt.org/certs/lets-encrypt-e1.pem -q -O ./certs/lets-encrypt-e1.pem
        openssl x509 -in ./certs/lets-encrypt-e1.pem -inform PEM -out ./certs/lets-encrypt-e1.crt
        sudo cp ./certs/lets-encrypt-r3.crt /usr/local/share/ca-certificates/
        sudo cp ./certs/lets-encrypt-e1.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates

### END CUSTOM KLUDGE

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Build release
      run: cargo build --verbose --target wasm32-wasi --release

    - name: Install hippofactory
      run: |
        mkdir -p tools/tmp
        wget https://github.com/deislabs/hippofactory/releases/download/v0.2.0/hippofactory-v0.2.0-linux-amd64.tar.gz -q -O ./tools/tmp/hippofactory.tar.gz
        tar xf ./tools/tmp/hippofactory.tar.gz -C ./tools

    - name: Publish bindle (tagged)
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./tools/hippofactory . -v production -o message

    - name: Publish bindle (main)
      if: github.ref == 'refs/heads/main'
      run: USER=canary ./tools/hippofactory . -o message
